# Generated by Django 5.2.3 on 2025-07-04 17:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('documento', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Cedula', 'Cédula')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('staff', 'Staff'), ('pasajero', 'Pasajero')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fila', models.CharField(max_length=25)),
                ('columna', models.CharField(max_length=25)),
                ('tipo', models.CharField(choices=[('economico', 'Económico'), ('premium', 'Premium'), ('ejecutivo', 'Ejecutivo')], max_length=12)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], max_length=12)),
                ('avion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.avion')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPasajero',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('documento', models.CharField(db_index=True, max_length=25)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('telefono', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Cedula', 'Cédula')], max_length=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pasajero',
                'verbose_name_plural': 'historical pasajeros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=12)),
                ('fecha_reserva', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_reserva', models.CharField(max_length=50, unique=True)),
                ('asiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_asiento', to='aerolinea.asiento')),
                ('pasajero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=30, unique=True)),
                ('fecha_emision', models.DateTimeField()),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('cancelado', 'Cancelado'), ('abordado', 'Abordado'), ('check-in realizado', 'Check-in Realizado')], max_length=25)),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vuelo', 'En vuelo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=12)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.avion')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='vuelo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_vuelo', to='aerolinea.vuelo'),
        ),
        migrations.CreateModel(
            name='HistoricalReserva',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=12)),
                ('fecha_reserva', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_reserva', models.CharField(db_index=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asiento_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aerolinea.asiento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pasajero_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aerolinea.pasajero')),
                ('vuelo_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aerolinea.vuelo')),
            ],
            options={
                'verbose_name': 'historical reserva',
                'verbose_name_plural': 'historical reservas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('vuelo_id', 'asiento_id'), ('vuelo_id', 'pasajero_id')},
        ),
    ]
