# Generated by Django 5.2.3 on 2025-07-04 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='reserva_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.reserva'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.IntegerField(),
        ),
    ]
